from hydrus.client import ClientConstants as CC
from hydrus.core import HydrusGlobals as HG
from hydrus.core import HydrusConstants as HC

enums = {
    "DuplicateTypes": {
        "DUPLICATE_POTENTIAL": HC.DUPLICATE_POTENTIAL,
        "DUPLICATE_FALSE_POSITIVE": HC.DUPLICATE_FALSE_POSITIVE,
        "DUPLICATE_SAME_QUALITY": HC.DUPLICATE_SAME_QUALITY,
        "DUPLICATE_ALTERNATE": HC.DUPLICATE_ALTERNATE,
        "DUPLICATE_BETTER": HC.DUPLICATE_BETTER,
        "DUPLICATE_SMALLER_BETTER": HC.DUPLICATE_SMALLER_BETTER,
        "DUPLICATE_LARGER_BETTER": HC.DUPLICATE_LARGER_BETTER,
        "DUPLICATE_WORSE": HC.DUPLICATE_WORSE,
        "DUPLICATE_MEMBER": HC.DUPLICATE_MEMBER,
        "DUPLICATE_KING": HC.DUPLICATE_KING,
        "DUPLICATE_CONFIRMED_ALTERNATE": HC.DUPLICATE_CONFIRMED_ALTERNATE
    }
}

tuples = {
    
}